//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unreal_Binary_Builder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutomationPath {
            get {
                return ((string)(this["AutomationPath"]));
            }
            set {
                this["AutomationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingHostPlatformOnly {
            get {
                return ((bool)(this["SettingHostPlatformOnly"]));
            }
            set {
                this["SettingHostPlatformOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithWin64 {
            get {
                return ((bool)(this["bWithWin64"]));
            }
            set {
                this["bWithWin64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithWin32 {
            get {
                return ((bool)(this["bWithWin32"]));
            }
            set {
                this["bWithWin32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithMac {
            get {
                return ((bool)(this["bWithMac"]));
            }
            set {
                this["bWithMac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithLinux {
            get {
                return ((bool)(this["bWithLinux"]));
            }
            set {
                this["bWithLinux"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithLinuxAArch64 {
            get {
                return ((bool)(this["bWithLinuxAArch64"]));
            }
            set {
                this["bWithLinuxAArch64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithHTML5 {
            get {
                return ((bool)(this["bWithHTML5"]));
            }
            set {
                this["bWithHTML5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithAndroid {
            get {
                return ((bool)(this["bWithAndroid"]));
            }
            set {
                this["bWithAndroid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithIOS {
            get {
                return ((bool)(this["bWithIOS"]));
            }
            set {
                this["bWithIOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithTVOS {
            get {
                return ((bool)(this["bWithTVOS"]));
            }
            set {
                this["bWithTVOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithSwitch {
            get {
                return ((bool)(this["bWithSwitch"]));
            }
            set {
                this["bWithSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bWithDDC {
            get {
                return ((bool)(this["bWithDDC"]));
            }
            set {
                this["bWithDDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bSignExes {
            get {
                return ((bool)(this["bSignExes"]));
            }
            set {
                this["bSignExes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bSymStore {
            get {
                return ((bool)(this["bSymStore"]));
            }
            set {
                this["bSymStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bCleanBuild {
            get {
                return ((bool)(this["bCleanBuild"]));
            }
            set {
                this["bCleanBuild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithPS4 {
            get {
                return ((bool)(this["bWithPS4"]));
            }
            set {
                this["bWithPS4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithXboxOne {
            get {
                return ((bool)(this["bWithXboxOne"]));
            }
            set {
                this["bWithXboxOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithLumin {
            get {
                return ((bool)(this["bWithLumin"]));
            }
            set {
                this["bWithLumin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Development;Shipping")]
        public string GameConfigurations {
            get {
                return ((string)(this["GameConfigurations"]));
            }
            set {
                this["GameConfigurations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithFullDebugInfo {
            get {
                return ((bool)(this["bWithFullDebugInfo"]));
            }
            set {
                this["bWithFullDebugInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Engine/Build/InstalledEngineBuild.xml")]
        public string CustomBuildXML {
            get {
                return ((string)(this["CustomBuildXML"]));
            }
            set {
                this["CustomBuildXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShutdownWindows {
            get {
                return ((bool)(this["bShutdownWindows"]));
            }
            set {
                this["bShutdownWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShutdownIfSuccess {
            get {
                return ((bool)(this["bShutdownIfSuccess"]));
            }
            set {
                this["bShutdownIfSuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomOptions {
            get {
                return ((string)(this["CustomOptions"]));
            }
            set {
                this["CustomOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bHostPlatformDDCOnly {
            get {
                return ((bool)(this["bHostPlatformDDCOnly"]));
            }
            set {
                this["bHostPlatformDDCOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithServer {
            get {
                return ((bool)(this["bWithServer"]));
            }
            set {
                this["bWithServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithClient {
            get {
                return ((bool)(this["bWithClient"]));
            }
            set {
                this["bWithClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWithHoloLens {
            get {
                return ((bool)(this["bWithHoloLens"]));
            }
            set {
                this["bWithHoloLens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bZipBuild {
            get {
                return ((bool)(this["bZipBuild"]));
            }
            set {
                this["bZipBuild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZipPath {
            get {
                return ((string)(this["ZipPath"]));
            }
            set {
                this["ZipPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludePDB {
            get {
                return ((bool)(this["bIncludePDB"]));
            }
            set {
                this["bIncludePDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludeDEBUG {
            get {
                return ((bool)(this["bIncludeDEBUG"]));
            }
            set {
                this["bIncludeDEBUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludeDocumentation {
            get {
                return ((bool)(this["bIncludeDocumentation"]));
            }
            set {
                this["bIncludeDocumentation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludeExtras {
            get {
                return ((bool)(this["bIncludeExtras"]));
            }
            set {
                this["bIncludeExtras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludeSource {
            get {
                return ((bool)(this["bIncludeSource"]));
            }
            set {
                this["bIncludeSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludeFeaturePacks {
            get {
                return ((bool)(this["bIncludeFeaturePacks"]));
            }
            set {
                this["bIncludeFeaturePacks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludeSamples {
            get {
                return ((bool)(this["bIncludeSamples"]));
            }
            set {
                this["bIncludeSamples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIncludeTemplates {
            get {
                return ((bool)(this["bIncludeTemplates"]));
            }
            set {
                this["bIncludeTemplates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bFastCompression {
            get {
                return ((bool)(this["bFastCompression"]));
            }
            set {
                this["bFastCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EngineSelection {
            get {
                return ((int)(this["EngineSelection"]));
            }
            set {
                this["EngineSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompileDatasmithPlugin {
            get {
                return ((bool)(this["CompileDatasmithPlugin"]));
            }
            set {
                this["CompileDatasmithPlugin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VS2019 {
            get {
                return ((bool)(this["VS2019"]));
            }
            set {
                this["VS2019"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalyticsType {
            get {
                return ((string)(this["AnalyticsType"]));
            }
            set {
                this["AnalyticsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingHostPlatformEditorOnly {
            get {
                return ((bool)(this["SettingHostPlatformEditorOnly"]));
            }
            set {
                this["SettingHostPlatformEditorOnly"] = value;
            }
        }
    }
}
